name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: "ubuntu-latest"
    env:
      DATABASE_URL: postgres://oraculo:oraculo123@localhost:5432/oraculo
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Get name
        id: name
        run: echo "::set-output name=file_name::fga-eps-mds-2021-2-Oraculo-Profile-$(TZ='America/Sao_Paulo' date +'%m-%d-%Y-%H-%M-%S')-${{github.ref_name}}"
        
      - name: Run tests
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn run db:up
      - run: yarn run db:migrate
      - run: yarn run db:seeders

      - run: yarn run user:create # creates admin user
      - run: yarn run test --outputFile=test-results.json --json
      

      - name: Create JSON
        run:  python3 parser.py fga-eps-mds_${{ github.event.repository.name }}
        
      - name: Make release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
           test-results.json

      - name: Pushes sonar file
        uses: dmnemec/copy_file_to_another_repo_action@80732d64341473fa7165a3b2b6c7b0ee164193f8
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: test-results.json
          destination_repo: "fga-eps-mds/2021-2-Oraculo-Doc"
          destination_branch: "master"
          destination_folder: "analytics-raw-data"
          user_email: ${{ secrets.USER_EMAIL }}
          user_name: ${{ secrets.USER_NAME }}
          commit_message: 'Adding SonarCloud file - fga-eps-mds-2021_2-Oraculo-Profile-${{ steps.date.outputs.date }}.json'

      
